CREATE TABLE IF NOT EXISTS persons
(
    id       INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name     VARCHAR(255) DEFAULT NULL,
    surname  VARCHAR(255) DEFAULT NULL,
    birthday DATE         DEFAULT NULL
);